Update dependencies
aleximmer/Laplace pull request #221
Opened 2024-08-15 19:18 UTC by wiseodd

1. Updated `curvlinops` to `>= 2.0`. @f-dangel has just made a new release.
2. Move out `asdl` dependency out of the build system. It needs to be installed manually until @kazukiosawa uploaded a new release to PyPi.

@runame please create a new release & upload to PyPi if things here are OK.

2024-08-15 21:12 UTC, runame requested changes

2024-08-15 21:12 UTC, runame commented on README.md
> +pip install git+https://github.com/kazukiosawa/asdl
Kazuki just created a new PyPI release (0.1a4), so let's use that.

2024-08-15 21:12 UTC, runame commented on .github/workflows/pytest.yml
> +          pip install git+https://github.com/kazukiosawa/asdl
can be removed

2024-08-15 21:12 UTC, runame commented on setup.cfg
> -    asdl @ git+https://github.com/kazukiosawa/asdl
Add `asdfghjkl == 0.1a4`.

2024-08-16 20:00 UTC, wiseodd commented
@runame please check

2024-08-19 11:02 UTC, aleximmer commented
Alternative that integrates old version of asdl into third_party at #224. Please don't merge either of them until we made a decision on how to best proceed.

2024-08-20 14:51 UTC, runame commented
@wiseodd @aleximmer Can this PR be closed?

2024-08-20 16:44 UTC, closed without merging